#default_language_version:
#  python: python3.12

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        files: ^ai/.*\.py$
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        files: ^ai/.*\.py$

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        files: ^server/.*\.rs$
        args: ["--manifest-path", "server/Cargo.toml", "--"]
      - id: cargo-check
        files: ^server/.*\.rs$
        args: ["--manifest-path", "server/Cargo.toml"]
      - id: clippy
        files: ^server/.*\.rs$
        args: ["--manifest-path", "server/Cargo.toml", "--", "-D", "warnings"]

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: ^gui/.*\.(c|h|cpp|hpp)$
