name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository != 'EpitechPGE2-2025/G-YEP-400-BAR-4-1-zappy-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          pip install pdoc

      - name: Create Public Directory
        run: mkdir -p public/gui public/server public/ai

      - name: Generate Doxygen (GUI & AI)
        run: doxygen docs/doxygen/Doxyfile
        # This will output to docs/doxygen/doxy-docs/html

      - name: Generate Rustdoc (Server)
        run: |
          source $HOME/.cargo/env
          cd server
          cargo doc --no-deps
        # This will output to server/target/doc

      - name: Organize Documentation
        run: |
          # Copy Doxygen output
          cp -r docs/doxygen/doxy-docs/html public/gui/
          # Copy Rustdoc output
          cp -r server/target/doc/* public/server/
          # Copy landing page
          cp docs/index.html public/
          # Generate AI documentation using pdoc
          pdoc ai/src -o public/ai

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
