name: Mirror Repository

on:
  push:
    branches: [ "*" ]
  tags:
    - "*"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository != 'EpitechPGE2-2025/G-YEP-400-BAR-4-1-zappy-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Target
        env:
          MIRROR_URL: ${{ secrets.MIRROR_TARGET_URL }}
        run: |
          if [ -z "$MIRROR_URL" ]; then
            echo "Error: MIRROR_TARGET_URL secret is not set."
            exit 1
          fi
          git push --mirror "$MIRROR_URL"
